---
- name: manage uptimerobot monitor entries
  tags: uptimerobot
  uptimerobot:
    api_key: "{{ uptimerobot_api_key }}"
    name: "{{ item.name }}"
    alert_contacts: "{{ alert_contacts }}"
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items:
  - "{{ uptimerobot_targets }}"

- name: manage uptimerobot alert entries
  tags: uptimerobot
  uptimerobot_alert:
    api_key: "{{ uptimerobot_api_key }}"
    alert_name: "{{ item.alert_name }}"
    alert_type: "{{ item.alert_type }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    status: "{{ item.status }}"
  with_items:
  - "{{ uptimerobot_alert_entries }}"
